# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2d062896eccf20157a0487ff1797bd338c2fdebb8c132666ab9dc6987f5da49889d14df29c06da55fc6957005a61a76c0bc5772bd8c41a9f949e38622857215

test:
  secret_key_base: 0e5e026a63a1508c659dfc9d6cd9a8d1eef0b729bfd98e3a33fd252c3cbc4bf99e2e5d99d5029f456d543f8b5a479114e2397854bab61a556c03801fbd24f84f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
